### ISSUE TITLE
DyanmoDB "UpdateItem" Support

### ISSUE THREAD

**Issue by sparkyrider** [KumologicaHQ/kumologica-support#3] opened 2021-04-09 22:01 UTC
Kumologica supports DynamoDB "PutItem" support, however, there is not support for "UpdateItem". This requires 2db calls (one to grab the item, throw it in memory, then "Put" the item with the new information added. 

Is "UpdateItem" possible to enable inside of Kumologica?

**Comment by bjq-dev** [comment] 2021-04-10 11:05
We are assessing feasibility of this change and timeline. It has definitely merit to have this operation supported. 
I will update with more information in next few days.

**Comment by sparkyrider** [comment] 2021-04-10 17:49
Awesome, thanks so much. This tool has helped a ton.

**Comment by bjq-dev** [comment] 2021-04-13 00:14
updateItem operation will be included into upcoming 2.0.9 release. 
We are planning for 2.0.9 release some time next week: 18.04.21 - 24.04.21

**Comment by sparkyrider** [comment] 2021-04-13 17:29
Awesome, thanks. Is there a beta release channel anywhere that we could subscribe to?

**Comment by jteso** [comment] 2021-04-15 04:45
We don't have beta release channel for core nodes yet. However if you are interested, we will be soon releasing the beta version of our Kumologica SDK that you can use to develop your own nodes.  If you are interested in participate in the beta testing, you can use our contact form from our website to request early access.

**Comment by sparkyrider** [comment] 2021-04-18 17:47
Yes, that would be awesome, it actually may help with the other issue I opened #4 regarding MySQL. I'll reach out, thanks so much!

**Comment by bjq-dev** [comment] 2021-04-25 10:33
kumologica designer 2.0.9 in pre-release testing

**Comment by bjq-dev** [comment] 2021-05-03 00:04
Changes released in designer 2.1.0

**Important Note**: All existing kumologica flows that need updateItem operation must change project.json kumologica-runtime dependency to runtime version: ^2.1.0. 

New projects created by designer 2.1.0 by default use new runtime version of 2.1.0

**Closed as completed by bjq-dev** 2021-05-03 00:04 UTC

**Comment by sparkyrider** [comment] 2021-05-03 12:52
Update-Item works great, thanks again!
